### ISSUE TITLE
reconstruction algorithm of penumbral imaging ?

### ISSUE THREAD

**Issue by scf819** [jkunimune15/kodi-analysis#3]
Can you provide the relevant papers for penumbral imaging

**Comment by jkunimune** [comment]
Sure, my preferred resource is Patrick Adrian's _Rev. Sci. Instrum. 93_, 113540 (2022), [doi.org/10.1063/5.0101655](https://pubs.aip.org/aip/rsi/article/93/11/113540/2849365/X-ray-imaging-spectrometer-XRIS-for-studies-of).  It describes the instrument geometry this code is designed for and covers all the main deterministic reconstruction algorithms.  For information about the MCMC algorithm, see my _Rev Sci. Instrum. 95_, 063506 (2024), [doi.org/10.1063/5.0214641](https://pubs.aip.org/aip/rsi/article/95/6/063506/3299188/Quantification-and-visualization-of-uncertainties).
